=== uswitch/trustyle/theme.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Trustyle base theme config map",
  "description": "The core set of design tokens required by trustyle componenets. All themes should match this schema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "useCustomProperties",
    "breakpoints",
    "fonts",
    "fontSizes",
    "fontWeights",
    "colors",
    "lineHeights",
    "letterSpacings",
    "radii",
    "shadows",
    "sizes",
    "space",
    "zIndices",
    "----------------------------- Root styles",
    "styles",
    "----------------------------- Variants",
    "elements",
    "compounds"
  ],

  "definitions": {
    "Indices": {
      "twelve": {
        "type": "object",
        "required": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        "additionalProperties": false,
        "minProperties": 12,
        "maxProperties": 12,
        "patternProperties": {
          "^(1[0-2]|[1-9])$": {
            "type": "integer", "minimum": 0
          }
        }
      },
      "four": {
        "type": "object",
        "required": [ "1", "2", "3", "4" ],
        "additionalProperties": false,
        "minProperties": 4,
        "maxProperties": 4,
        "patternProperties": {
          "^[1-4]$": {
            "type": "integer", "minimum": 0
          }
        }
      }
    },

    "BoxShadow": {
      "type": "string",
      "description": "Pattern which matches a box shadow",
      "pattern": "^[0-9]+px [0-9]+px [0-9]+px #([0-9]{3,4}|[0-9]{6,7})$"
    },

    "Radii": {
      "oneOf": [
        {
          "type": "integer",
          "minimum": 0
        },
        {
          "type": "string",
          "pattern": "^(100|[0-9]{1,2})%$"
        }
      ]
    },

    "FontWeight": {
      "type": "integer",
      "multipleOf": 100
    },

    "TshirtSizes": {
      "type": "object",
      "properties": {
        "base": { "type": "integer", "minimum": 0 },
        "xxs": { "type": "integer", "minimum": 0 },
        "xs": { "type": "integer", "minimum": 0 },
        "sm": { "type": "integer", "minimum": 0 },
        "md": { "type": "integer", "minimum": 0 },
        "lg": { "type": "integer", "minimum": 0 },
        "xl": { "type": "integer", "minimum": 0 },
        "xxl": { "type": "integer", "minimum": 0 },
        "xxxl": { "type": "integer", "minimum": 0 }
      }
    }
  },

  "properties": {
    "useCustomProperties": { "type": "boolean", "const": false },
    "name": {
      "type": "string",
      "description": "The name of the brand this theme defines"
    },

    "breakpoints": {
      "type": "array",
      "minLength": 2,
      "maxLength": 2,
      "items": {
        "type": "string",
        "pattern": "^[0-9]+px$",
        "description": "The two breakpoints for tablet & desktop"
      }
    },

    "fonts": {
      "type": "object",
      "required": [ "base", "heading", "monospace" ],
      "additionalProperties": false,
      "properties": {
        "base": { "type": "string", "description": "Base font for all text" },
        "heading": { "type": "string", "description": "Font specifically used by headings" },
        "monospace": { "type": "string", "description": "Font specifically used by monospace tags" }
      }
    },

    "colors": {
      "type": "object",
      "description": "List of colours available for the theme",
      "required": [
        "grey-0",
        "grey-05",
        "grey-10",
        "grey-20",
        "grey-30",
        "grey-40",
        "grey-50",
        "grey-60",
        "grey-70",
        "grey-80",
        "grey-90",
        "grey-100",
        "text",
        "brand"
      ],
      "patternProperties": {
        ".*": {
          "type": "string",
          "pattern": "^#[0-9A-Fa-f]{6}$",
          "description": "Hex code colour"
        }
      }
    },

    "fontWeights": {
      "type": "object",
      "properties": {
        "base": { "$ref": "#/definitions/FontWeight" },
        "light": { "$ref": "#/definitions/FontWeight" },
        "medium": { "$ref": "#/definitions/FontWeight" },
        "bold": { "$ref": "#/definitions/FontWeight" }
      }
    },

    "radii": {
      "type": "object",
      "properties": {
        "sm": { "$ref": "#/definitions/Radii" },
        "md": { "$ref": "#/definitions/Radii" },
        "lg": { "$ref": "#/definitions/Radii" },
        "xl": { "$ref": "#/definitions/Radii" },
        "round": { "enum": [ "50%", "0" ] }
      }
    },


    "letterSpacings": {
      "type": "object",
      "properties": {
        "base": { "type": "number" },
        "wide": { "type": "number" },
        "narrow": { "type": "number" }
      }
    },


    "lineHeights": {
      "type": "object",
      "properties": {
        "base": { "type": "number" },
        "lg": { "type": "number" }
      }
    },

    "shadows": {
      "low": { "$ref": "#/definitions/BoxShadow" },
      "medium": { "$ref": "#/definitions/BoxShadow" },
      "high": { "$ref": "#/definitions/BoxShadow" }
    },

    "fontSizes": {
      "$ref": "#/definitions/TshirtSizes"
    },

    "space": {
      "$ref": "#/definitions/TshirtSizes"
    },

    "sizes": {
      "type": "object",
      "requied": [ "grid" ],
      "properties": {
        "grid": {
          "type": "object",
          "required": [ "lg", "md", "sm" ],
          "additionalProperties": false,
          "properties": {
            "lg-docs": { "type": "string" },
            "md-docs": { "type": "string" },
            "sm-docs": { "type": "string" },
            "lg": { "$ref": "#/definitions/Indices/twelve" },
            "md": { "$ref": "#/definitions/Indices/twelve" },
            "sm": { "$ref": "#/definitions/Indices/four" }
          }
        }
      }
    },

    "zIndices": {
      "type": "object",
      "properties": {
        "level": { "$ref": "#/definitions/Indices/twelve" },
        "max": {
          "type": "integer",
          "minimum": 999
        }
      }
    },

    "----------------------------- Root styles": {
      "description": "Marker to separate root styles",
      "const": "-----------------------------"
    },

    "styles": {
      "type": "object",
      "required": [
        "root", "h1", "h2", "h4", "h5", "h6", "pre", "code", "table", "th", "td"
      ],
      "description": "Base styles for semantic HTML elements to inherit from as a <Styled.tag /> component",
      "additionalProperties": false,
      "properties": {
        "root": { "type": "object" },
        "h1": { "type": "object" },
        "h2": { "type": "object" },
        "h3": { "type": "object" },
        "h4": { "type": "object" },
        "h5": { "type": "object" },
        "h6": { "type": "object" },
        "pre": { "type": "object" },
        "code": { "type": "object" },
        "table": { "type": "object" },
        "th": { "type": "object" },
        "td": { "type": "object" },
        "tr": { "type": "object" },
        "p": { "type": "object" },
        "a": { "type": "object" },
        "blockquote": { "type": "object" }
      }
    },

    "----------------------------- Variants": {
      "description": "Marker to separate root styles",
      "const": "--------------------------------"
    },

    "elements": {
      "type": "object",
      "description": "An object of that can be used by elements"
    },

    "compounds": {
      "type": "object",
      "description": "An object of that can be used by elements"
    }
  }
}

=== uswitch/trustyle/src/utils/theme-composer/src/money-theme.json
{
  "name": "Money",
  "useCustomProperties": false,
  "breakpoints": [
    "768px",
    "990px"
  ],
  "fonts": {
    "base": "'Open Sans', -apple-system, sans-serif",
    "heading": "Nunito, -apple-system, sans-serif",
    "monospace": "Menlo, monospace"
  },
  "colors": {
    "grey-0": "#FFFFFF",
    "grey-05": "#F7F7F7",
    "grey-10": "#F2F2F3",
    "grey-20": "#DFDFE1",
    "grey-30": "#C2C4C8",
    "grey-40": "#ADAFB3",
    "grey-50": "#A0A2A6",
    "grey-60": "#6D6F73",
    "grey-70": "#393B3F",
    "grey-80": "#24262A",
    "grey-90": "#111317",
    "grey-100": "#000000",
    "text": "#000000",
    "brand": "#000000"
  },
  "fontSizes": {
    "base": 16,
    "xxs": 12,
    "xs": 14,
    "sm": 16,
    "md": 18,
    "lg": 20,
    "xl": 24,
    "xxl": 30,
    "xxxl": 36
  },
  "fontWeights": {
    "base": 400,
    "light": 300,
    "medium": 500,
    "bold": 600
  },
  "letterSpacings": {
    "base": 1,
    "wide": 2,
    "narrow": 0.5
  },
  "lineHeights": {
    "base": 1.2,
    "lg": 1.5
  },
  "radii": {
    "sm": 3,
    "md": 6,
    "lg": 16,
    "xl": 30,
    "round": "50%"
  },
  "shadows": {
    "low": "2px 2px 25px #0004",
    "medium": "2px 2px 25px #0004",
    "high": "2px 2px 25px #0004"
  },
  "sizes": {
    "grid": {
      "lg-docs": "// 84 + 16 gutter up to 12 columns",
      "lg": {
        "1": 82,
        "2": 180,
        "3": 278,
        "4": 376,
        "5": 474,
        "6": 572,
        "7": 670,
        "8": 768,
        "9": 866,
        "10": 964,
        "11": 1062,
        "12": 1160
      },
      "md-docs": "// 64 + 16 gutter up to 12 columns",
      "md": {
        "1": 64,
        "2": 144,
        "3": 224,
        "4": 304,
        "5": 384,
        "6": 464,
        "7": 544,
        "8": 624,
        "9": 704,
        "10": 784,
        "11": 864,
        "12": 944
      },
      "sm-docs": "// 58 + 16 gutter up to 12 columns",
      "sm": {
        "1": 58,
        "2": 132,
        "3": 206,
        "4": 280
      }
    }
  },
  "space": {
    "base": 16,
    "xxs": 4,
    "xs": 8,
    "sm": 16,
    "md": 24,
    "lg": 32,
    "xl": 48,
    "xxl": 64,
    "xxxl": 96
  },
  "zIndices": {
    "level": {
      "1": 10,
      "2": 20,
      "3": 30,
      "4": 40,
      "5": 50,
      "6": 60,
      "7": 70,
      "8": 80,
      "9": 90,
      "10": 100,
      "11": 110,
      "12": 120
    },
    "max": 999
  },
  "----------------------------- Root styles": "-----------------------------",
  "styles": {
    "root": {
      "fontFamily": "body",
      "lineHeight": "body",
      "fontWeight": "body"
    },
    "h1": {
      "variant": "text.heading",
      "fontSize": 5
    },
    "h2": {
      "variant": "text.heading",
      "fontSize": 4
    },
    "h3": {
      "variant": "text.heading",
      "fontSize": 3
    },
    "h4": {
      "variant": "text.heading",
      "fontSize": 2
    },
    "h5": {
      "variant": "text.heading",
      "fontSize": 1
    },
    "h6": {
      "variant": "text.heading",
      "fontSize": 0
    },
    "pre": {
      "fontFamily": "monospace",
      "overflowX": "auto",
      "code": {
        "color": "inherit"
      }
    },
    "code": {
      "fontFamily": "monospace",
      "fontSize": "inherit"
    },
    "table": {
      "width": "100%",
      "borderCollapse": "separate",
      "borderSpacing": 0
    },
    "th": {
      "textAlign": "left",
      "borderBottomStyle": "solid"
    },
    "td": {
      "textAlign": "left",
      "borderBottomStyle": "solid"
    }
  },
  "----------------------------- Variants": "--------------------------------",
  "elements": {
    "accordion": {
      "base": {
        "marginTop": "sm",
        "marginBottom": "sm",
        "title": {
          "marginTop": "0",
          "marginBottom": "xs"
        },
        "content": {
          "marginBottom": "xs"
        },
        "button": {
          "padding": "0",
          "paddingTop": 10,
          "paddingBottom": 10,
          "bg": "transparent",
          "fontFamily": "base",
          "fontSize": "base",
          "fontWeight": "bold",
          "color": "textColor",
          "alignItems": "center",
          "borderWidth": "1px 0 0 0",
          "borderStyle": "solid",
          "borderColor": "grey-20",
          "display": "flex",
          "flexDirection": "row",
          "width": "100%"
        },
        "caret": {
          "color": "plum"
        }
      },
      "variants": {
        "isActive": {
          "button": {
            "variant": "accordion.base.button"
          },
          "caret": {
            "color": "fuschia"
          }
        }
      }
    },
    "author": {
      "heading": {
        "color": "grey-80"
      },
      "link": {
        "color": "grey-80",
        ":hover": {
          "color": "plum"
        }
      }
    },
    "author-profile": {
      "main": {
        "marginBottom": "xl"
      },
      "name": {
        "a": {
          "color": "grey-80"
        }
      }
    },
    "badge": {
      "base": {
        "paddingX": "base",
        "paddingY": [
          3,
          5.5
        ],
        "fontSize": [
          "xs",
          "sm"
        ],
        "fontWeight": "bold",
        "borderRadius": "50vh"
      },
      "variants": {
        "primary": {
          "variant": "badge.base",
          "backgroundColor": "plum",
          "color": "white"
        }
      }
    },
    "breadcrumbs": {
      "base": {
        "main": {
          "color": "grey-60"
        },
        "homeIcon": {
          "color": "grey-60"
        },
        "title": {
          "color": "grey-100"
        }
      },
      "variants": {
        "light": {
          "main": {
            "color": "grey-0"
          },
          "mobileLink": {
            "color": "grey-0"
          },
          "homeIcon": {
            "color": "grey-0"
          },
          "title": {
            "color": "grey-0"
          }
        }
      }
    },
    "button": {
      "base": {
        "fontWeight": "bold",
        "border": "none",
        "borderRadius": "50vh",
        ":disabled": {
          "opacity": "0.3",
          "cursor": "not-allowed"
        },
        "btnSize": {
          "large": {
            "paddingX": "xl",
            "paddingY": "base",
            "fontSize": "md",
            "height": 56
          },
          "small": {
            "paddingX": 40,
            "paddingY": 13,
            "fontSize": "sm",
            "height": "xl"
          }
        }
      },
      "variants": {
        "primary": {
          "variant": "buttons.base",
          "color": "experimental-text",
          "backgroundColor": "primary",
          ":hover:not(:disabled)": {
            "backgroundColor": "primary--dark"
          },
          ":focus": {
            "backgroundColor": "primary--dark"
          },
          ":active": {
            "backgroundColor": "primary--dark"
          }
        },
        "secondary": {
          "variant": "buttons.base",
          "color": "grey-0",
          "backgroundColor": "button-secondary",
          ":hover:not(:disabled)": {
            "backgroundColor": "button-secondary--hover"
          },
          ":focus": {
            "backgroundColor": "button-secondary--hover"
          },
          ":active": {
            "backgroundColor": "button-secondary--hover"
          }
        }
      }
    },
    "call-out": {
      "main": {
        "backgroundColor": "grey-10",
        "paddingX": [
          "sm",
          "md"
        ]
      },
      "icon": {
        "backgroundColor": "plum"
      }
    },
    "cta": {
      "base": {
        "main": {
          "backgroundColor": "grey-10"
        },
        "title": {
          "color": "experimental-text",
          "fontWeight": "bold"
        },
        "text": {
          "marginBottom": [
            null,
            0
          ]
        },
        "button": {
          "marginLeft": [
            null,
            "md"
          ]
        }
      },
      "variants": {
        "hero": {
          "main": {
            "backgroundColor": "none",
            "color": "white"
          },
          "title": {
            "variant": "cta2.base.title",
            "color": "inherit"
          },
          "text": {
            "variant": "cta2.base.text"
          },
          "button": {
            "variant": "cta2.base.button"
          }
        },
        "hero-white-bg": {
          "main": {
            "backgroundColor": "white"
          },
          "title": {
            "variant": "cta2.base.title"
          },
          "text": {
            "variant": "cta2.base.text"
          },
          "button": {
            "variant": "cta2.base.button"
          }
        }
      }
    },
    "funnel-progress": {
      "base": {
        "display": "flex",
        "flexFlow": "row",
        "userSelect": "none",
        "phase": {
          "base": {
            "flex": "1",
            "flexGrow": 0,
            "marginLeft": "5px",
            "background": "#E6F4FD",
            "borderRadius": "999px",
            "whiteSpace": "nowrap",
            "position": "relative",
            "transition": "flex-grow 0.4s",
            "&:first-child": {
              "marginLeft": "0px"
            }
          },
          "variants": {
            "open": {
              "variant": "funnelProgress.base.phase.base",
              "flexGrow": 1,
              "overflow": "hidden"
            }
          }
        },
        "phaseLabel": {
          "base": {
            "position": "relative",
            "whiteSpace": "nowrap",
            "overflow": "hidden",
            "textOverflow": "ellipsis"
          }
        },
        "phaseLabelPart": {
          "base": {
            "display": "inline-block",
            "verticalAlign": "top",
            "marginLeft": "4px",
            "fontSize": "14px",
            "fontWeight": "bold",
            "lineHeight": "24px",
            "color": "#002396",
